title: resilienceforgrowth.com
description: Un lugar para encontrar la paz
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://resilienceforgrowth.com.github.io" # the base hostname & protocol for your site
theme: minima
markdown: kramdown
paginate: 5

# Build settings
plugins:
  - jekyll-feed
