title: My Jekyll Site
description: A simple description of your site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://your-site.github.io" # the base hostname & protocol for your site
theme: minima
markdown: kramdown
paginate: 5

# Build settings
plugins:
  - jekyll-feed
