title: resilienceforgrowth.com
description: Un lugar para encontrar la paz
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://resilienceforgrowth.com.github.io" # the base hostname & protocol for your site
author: "Javier Rodríguez y Lara I. Batista"
theme: minima
markdown: kramdown
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  - jekyll-admin

# Optional settings
timezone: "Europe/Madrid" # Ajuste según su zona horaria
language: "es"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby